### ISSUE TITLE
Task built runs on Windows 11, but not on Windows 10

### ISSUE THREAD

**Issue by anvo2** [brown-ccv/neuro-task-starter#103]
Hi,

While trying to run the execute of [https://github.com/lnccbrown/task-effort/tree/No-EEG-Event-Codes](url) on a clean windows 10 machine, I ran into this Squirrel error 

![image](https://user-images.githubusercontent.com/84743377/182192278-414f0a72-86ce-4ebb-8ddb-5f788b64ff98.png)

the execute runs fine on Windows 11. A hasty google search didn't give me much lead to go on :( I'd greatly appreciate a hand with this :)

**Comment by mirestrepo** [comment]
Hi @anvo2  - Are you at Brown? I think there are several Windows troubles happening with the lncc effort task, and we will probably need some longer sessions to help out. We can probably set something out with the lab to help out

**Comment by mirestrepo** [comment]
And I'm sorry if I know you, GitHub handles are hard!

**Comment by mirestrepo** [comment]
And is the error on a `npm install` on when actually running?

**Comment by mirestrepo** [comment]
I'm going to close this due to inactivity. If you still need help. Try our Discussions
