### ISSUE TITLE
docs: How should Firebase be run in dev?

### ISSUE THREAD

**Issue by mirestrepo** [brown-ccv/neuro-task-starter#122]
Use emulator? What scripts are the recommended ones from `package.json`?

**Comment by RobertGemmaJr** [comment]
Updated `dev:firebase` to run in the browser instead of Electron. It now uses the Firebase emulator data.

Will have to update the docs to reflect this. I also renamed `firebase:dev` as `firebase:emulators:start` which will have to be run in a separate terminal
