### ISSUE TITLE
fix: Experiment data may exceed Firebase 1Mb document limit

### ISSUE THREAD

**Issue by mirestrepo** [brown-ccv/neuro-task-starter#130]
At the moment all of the results of an experiment are saved to the same document. For some experiments, this is exceeding the 1MB limit for Firestore. We should break results into multiple documents, which may imply a deeper collection/document structure [here](https://github.com/brown-ccv/honeycomb/blob/b9e817ee6e68f4b697e7966dd94ff476032a618a/src/firebase.js#L48).

We also should look into [Firebase best practices](https://firebase.google.com/docs/firestore/best-practices) - there are references to continuous indexing that can lead to hot spotting that may be important to think about.

**Comment by RobertGemmaJr** [comment]
Right now Firebase is writing to Firestore at the end of EVERY trial - not just once the experiment is completed. Is it possible some of the issues here have to do with the number of writes to the database we're doing?

**Comment by mirestrepo** [comment]
I really think the issue is mostly about the document size. I think the write frequency depends on experiment. Some care about partial responses, some don't. I'm not sure if we could make this configurable.

**Comment by RobertGemmaJr** [comment]
Okay I think I figured it out... the nested document/collection structure can be done for each trial within an experiment


Right now the leaf document is an array of every single trial:
- participant_responses
  - `studyID`
    - participants
      - `participantID`
        - data
          - `startDate`
            - `{results: [trial1, trial2, trial3]}` (each is a trial object created by JsPsych)
          
```js
const collectionName = "participant_responses";
const addToFirebase = (data) => {
  console.log("Adding trial to firebase", data)
  const participantId = data.participant_id;
  const studyId = data.study_id;
  const startDate = data.start_date

  db.collection(collectionName) 
    .doc(studyId)
    .collection('participants')
    .doc(participantId)        
    .collection('data')         
    .doc(startDate)
    // results IS AN ARRAY OF EVERY TRIAL I NTHE EXPERIMENT
    .update('results', firebase.firestore.FieldValue.arrayUnion(data))
};
```

We need to make each trial it's own document by nesting them as their own collection:
- participant_responses
  - `studyID`
    - participants
      - `participantID`
        - data
          - `startDate`
            - trials
              - `trialID`
                - // trial object created by JsPsych

To do this we need to give each trial its own ID, which I think JsPsych already handles. Should be pretty easy to implement but is DEFINITELY a huge breaking change for people who already have a bunch of experiments saved.

Excuse my poor handwriting but I think this is what we should be looking to do. I figure if we're going to be making a huge breaking change we might as well name things better while we're at it? We could also look to make each unique study its own collection (deleting the "studies" collection at the root). Not sure which will be better for the end user

![IMG-8461](https://user-images.githubusercontent.com/38439940/222838844-76165a20-f936-4a2c-9242-40ef0ce0333a.JPG)
