### ISSUE TITLE
Clearer understanding of verbiage

### ISSUE THREAD

**Issue by RobertGemmaJr** [brown-ccv/neuro-task-starter#141]
Can be better outlined in the docs and in code, the common verbiage for researches isn't necessarily outlined well.

The way I understand it
- **Trial:** is a single task within an experiment
- **Timeline:** A selection of trials, their order, and frequency for a given experiment

I would think "trial" should be "task" and a trial is a single run-through of the experiment but I don't known enough of the research terms to know if it's something everyone in the field knows

**Comment by RobertGemmaJr** [comment]
Looks like "trials" is coming from `jspsych`?

**Comment by digicosmos86** [comment]
I am just learning this from [here](https://www.jspsych.org/7.3/overview/timeline/), but yes, a `timeline` consists of multiple trails, and the way I understand it, a `timeline` is the abstraction for what we call `task`
