### ISSUE TITLE
Build_and_preview job failing on multiple GitHub deployments to firebase.

### ISSUE THREAD

**Issue by rossan750** [brown-ccv/neuro-task-starter#179]
I'm at 2:08:25 in this video:

https://brown.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=5a27b4d5-f6da-4490-a9fb-aefc0154c7e4

The "replace task with simple jspsych 7 task" action is failing for me, specifically the build_and_preview job in that action. The log indicates the error:

"RequestError [HttpError]: Resource not accessible by integration"

I'm also seeing in my actions history that a lot of deployments to Firebase have failed at the build_and_preview job. The error indicated in some of those:

"Error: Input required and not supplied: firebaseServiceAccount"

I suspect this is a permissions issue, but I don't know what permissions need to be changed. Any assistance would be appreciated.

EDIT: Should clarify this is on Mac OS.

**Comment by RobertGemmaJr** [comment]
How much of your firebase account have you already set up? We have office hours on Fridays from 10-12 if you are available then to chat over zoom?

**Comment by rossan750** [comment]
Hi Robert! Thanks for getting back to me. You can see what workflows I have either attempted or been able to successfully execute in the image below. I've gone through most of the set up. Also, something to note: my repository was originally set to read only as opposed to read and write. Changing the repository settings to read and write allowed the feat(timelines) action to execute successfully, but didn't fix anything else. How does a Zoom meeting at 11 this Friday sound?


![image](https://user-images.githubusercontent.com/31392769/234689137-e8f8cc9f-2796-4295-86aa-da71935a8a34.png)

**Comment by RobertGemmaJr** [comment]
Apologies for the delayed response as I've been on vacation the last few weeks. Were you able to get help from anyone else at the CCV office hours?

It definitely appears as though your issue has something to do with the Firebase project. Do you know the name of the project you created? I'll take a look and see if I can change the permissions myself otherwise we can set up a zoom meeting

**Comment by rossan750** [comment]
Here is my Honeycomb set up: https://github.com/rossan750/my_honeycomb_app

And yes, it looks like this is Firebase-related. I'd definitely be open to a Zoom call if that's necessary.

**Comment by RobertGemmaJr** [comment]
Here's our event for office hours tomorrow!

https://events.brown.edu/ccv/event/246869-ccv-office-hours

**Comment by rossan750** [comment]
Thank you!

**Comment by RobertGemmaJr** [comment]
We were able to resolve both issues in office hours. Will add documentation to for the other issues

- https://github.com/brown-ccv/honeycomb-docs/issues/57
- https://github.com/brown-ccv/honeycomb-docs/issues/56
