### ISSUE TITLE
White blinking screen (ca. 200ms) between each trial

### ISSUE THREAD

**Issue by ulfjakob** [brown-ccv/neuro-task-starter#309]
There is a white blinking screen between trials of around 100-200ms. This can be seen in the default task (such as it is in the repo). I do not have this same issue with this task (or others) when running jspsych, e.g. following the jspsych tutorial.

Is there a way to avoid this white blinking screen?

**Comment by RobertGemmaJr** [comment]
@ulfjakob  The script `dev:clinic` automatically loads environment variables from `env/.env.clinic`, and `REACT_APP_USE_PHOTODIODE` is what causes the blinking screen. Ruining `dev:home` does not set that environment variable

**Comment by RobertGemmaJr** [comment]
It will also depend on which trial(s) you are running

**Comment by ulfjakob** [comment]
@RobertGemmaJr thank you for your response. 

It seems I was not quite clear in my post. What I mean is there is a short delay between between when each trial ends, and the next one begins, which just shows an empty white screen.

**Comment by RobertGemmaJr** [comment]
I would check to see if there's a `post_trial_gap` set for any/all of the trials. It's a parameter to all jspsych trials: https://www.jspsych.org/7.3/overview/plugins/#parameters-available-in-all-plugins
