### ISSUE TITLE
[BUG] Universal and cross-chip building on macOS not packaging correct arch

### ISSUE THREAD

**Issue by celstark** [brown-ccv/neuro-task-starter#318]
**Describe the bug**
Universal or cross-chip building not functioning on Mac. Using an Apple Silicon Mac, we should be able to not only build for native (arm64), but also for Intel x86_64 and we should be able to make a fat binary that has both. Much of this is operating correctly with electron-forge, but there is a component I've not isolated that is not being properly packaged and is only including native code.

**To Reproduce**
1. Clone honeycomb from the repo and `nom run dev` to check out the sample app.
2. Build an Intel (x86_64) on Apple Silicon or build a Universal on Apple Silicon
```
    "package:mac-universal": "react-scripts build && electron-forge make --arch universal --targets @electron-forge/maker-dmg",
    "package:mac-arm": "react-scripts build && electron-forge make --arch arm64 --targets @electron-forge/maker-dmg",
    "package:mac-intel": "react-scripts build && electron-forge make --arch x64 --targets @electron-forge/maker-dmg"
```
3. Try to run either on Intel _or_ try to run the x86 build on Apple Silicon

**Expected behavior**
The program should start and operate normally.  A Universal / fat binary should run on either platform. An M2-built Intel should run on Intel (and on the M2 via Rosetta).

**Screenshots**
Here's what happens when you run the x64 build (built on M2) on an Intel Mac:
<img width="260" alt="Screen Shot 2023-11-12 at 5 46 52 PM" src="https://github.com/brown-ccv/honeycomb/assets/9575070/84c6ecca-6cec-46b9-acb6-3aa7c42e2339">
<img width="253" alt="Screen Shot 2023-11-12 at 5 47 16 PM" src="https://github.com/brown-ccv/honeycomb/assets/9575070/82d249b5-4514-4596-b2d0-f26157712f6e">

Note, the Universal does the same thing (it just glues the Intel and Apple binaries together in one package).

Here's what happens if you run the x64 on M2.  This should run given Rosetta2, but it doesn't and the error is also indicating that it's trying to run it as x64, but that it's got some arm64 code in there.  Is says "have arm64... need x86_64".  So, the Intel build is still packaging some arm code in there.
<img width="515" alt="Intel_Run_on_M2" src="https://github.com/brown-ccv/honeycomb/assets/9575070/ddcd57d6-c8af-4b92-98ba-ad43f09c9508">

**Desktop (please complete the following information):**
 - OS: macOS

**Additional context**
Electron-forge is doing a lot right here. We can see that they're built correctly:
```
(base) stark@dhcp-172-31-224-166 out % for i in honeycomb-darwin-*; do echo $i; lipo -detailed_info $i/honeycomb.app/Contents/MacOS/honeycomb; done

honeycomb-darwin-arm64
input file honeycomb-darwin-arm64/honeycomb.app/Contents/MacOS/honeycomb is not a fat file
Non-fat file: honeycomb-darwin-arm64/honeycomb.app/Contents/MacOS/honeycomb is architecture: arm64

honeycomb-darwin-universal
Fat header in: honeycomb-darwin-universal/honeycomb.app/Contents/MacOS/honeycomb
fat_magic 0xcafebabe
nfat_arch 2
architecture x86_64
    cputype CPU_TYPE_X86_64
    cpusubtype CPU_SUBTYPE_X86_64_ALL
    capabilities CPU_SUBTYPE_LIB64
    offset 4096
    size 17176
    align 2^12 (4096)
architecture arm64
    cputype CPU_TYPE_ARM64
    cpusubtype CPU_SUBTYPE_ARM64_ALL
    capabilities 0x0
    offset 32768
    size 50472
    align 2^14 (16384)

honeycomb-darwin-x64
input file honeycomb-darwin-x64/honeycomb.app/Contents/MacOS/honeycomb is not a fat file
Non-fat file: honeycomb-darwin-x64/honeycomb.app/Contents/MacOS/honeycomb is architecture: x86_64
```

So, building for x64 gets us x64, for arm64 gets us arm64, and for Universal gets us both. Traversing into the actual .app folder and running the same code shows that the right architectures are in the Frameworks folder and the helper .app files are also built correctly. The one thing that I can see in here is the `app.asar` bit.  I'm not familiar with it (beyond 10s of Google telling me it's electron's tar), but a lot sure points to that `asar` packaging being the culprit.

**Comment by celstark** [comment]
Your note in #312 about the serial port was on-target.  I'd tried a bit of that before, but @seriaport was still getting packaged. The trick was to not only pull all of the trigger / port bits from electron.js but also to pull event-marker from package.json.  With all of this extracted, we do build a functioning universal.

That said, it does seem as if both architectures are available for your serial port code, so this is more a patch than a fix. 

Thanks

**Comment by RobertGemmaJr** [comment]
Thank you for the context! This does give me some hope for the actual fix.

We're looking to refactor that code to use Electron's web serial API (more [here](https://www.electronjs.org/docs/latest/tutorial/devices#web-serial-api)). We anticipate being able to remove the `event-marker` dependency once that change is made. Hopefully that means we'll only need the `universal` build.
