### ISSUE TITLE
Upgrade general dependencies

### ISSUE THREAD

**Issue by mcmcgrath13** [brown-ccv/neuro-task-starter#93]
NPM yells an increasing number of deprecation/security warnings on each install - it's time to comb through and upgrade all of the project dependencies.

**Comment by RobertGemmaJr** [comment]
**Packages to update**
- [ ] @fortawesome/fontawesome-free
- [ ] execa
- [ ] fs-extra 
- [ ] popper.js
- [ ] react
- [ ] react-bootstrap 
- [ ] react-dom
- [ ] typescript
- [ ] babel-plugin-macros
- [ ] concurrently 
- [ ] dotenv
- [ ] dotenv-cli
- [ ] electron

**Not used?**

- [ ] @jspsych/plugin-image-keyboard-response
- [ ] electron-log
- [ ] electron-squirrel-startup
- [ ] @electron-forge/maker-deb
- [ ] @electron-forge/maker-dmg
- [ ] @electron-forge/maker-squirrel

**NOTES**
- React should be pulled into its own PR
- electron should be its own PR (may not be possible?)
- typescript can be removed (#95)
- `npm-check` revealed a package error for underscore?

**Comment by RobertGemmaJr** [comment]
Closing, will split into multiple issues
